### ISSUE TITLE
unmovable black box appears on the client after sending about 500000 requests to server

### ISSUE THREAD

**Issue by prescott2m** [IanBotashev/messenger#1]
![image](https://github.com/IanBotashev/messenger/assets/49623720/7bd6e0d8-dbeb-46aa-bf51-aa0edd27f51b)

full error log:

```
2023-07-20 21:12:25-0700 [Client,client] Unhandled Error
        Traceback (most recent call last):
          File "/home/winksplorer/.local/lib/python3.11/site-packages/twisted/python/log.py", line 96, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/winksplorer/.local/lib/python3.11/site-packages/twisted/python/log.py", line 80, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/winksplorer/.local/lib/python3.11/site-packages/twisted/python/context.py", line 117, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/winksplorer/.local/lib/python3.11/site-packages/twisted/python/context.py", line 82, in callWithContext
            return func(*args, **kw)
        --- <exception caught here> ---
          File "/home/winksplorer/.local/lib/python3.11/site-packages/twisted/internet/posixbase.py", line 487, in _doReadOrWrite
            why = selectable.doRead()
          File "/home/winksplorer/.local/lib/python3.11/site-packages/twisted/internet/tcp.py", line 248, in doRead
            return self._dataReceived(data)
          File "/home/winksplorer/.local/lib/python3.11/site-packages/twisted/internet/tcp.py", line 253, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/home/winksplorer/Downloads/messenger/client.py", line 38, in dataReceived
            CTkMessagebox(title="Client Error", message="Something went wrong with the client. Try again.", icon="close", master=self.gui)
          File "/home/winksplorer/.local/lib/python3.11/site-packages/CTkMessagebox/ctkmessagebox.py", line 192, in __init__
            self.icon = self.load_icon(icon, icon_size) if icon else None
          File "/home/winksplorer/.local/lib/python3.11/site-packages/CTkMessagebox/ctkmessagebox.py", line 335, in load_icon
            self.ICONS[icon] = customtkinter.CTkImage(Image.open(image_path), size=size)
          File "/home/winksplorer/.local/lib/python3.11/site-packages/PIL/Image.py", line 3218, in open
            fp = builtins.open(filename, "rb")
        builtins.FileNotFoundError: [Errno 2] No such file or directory: 'close'

2023-07-20 21:12:25-0700 [Client,client] Lost connection.  Reason: [Failure instance: Traceback: <class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'close'
        /home/winksplorer/.local/lib/python3.11/site-packages/twisted/python/log.py:80:callWithContext
        /home/winksplorer/.local/lib/python3.11/site-packages/twisted/python/context.py:117:callWithContext
        /home/winksplorer/.local/lib/python3.11/site-packages/twisted/python/context.py:82:callWithContext
        /home/winksplorer/.local/lib/python3.11/site-packages/twisted/internet/posixbase.py:500:_doReadOrWrite
        --- <exception caught here> ---
        /home/winksplorer/.local/lib/python3.11/site-packages/twisted/internet/posixbase.py:487:_doReadOrWrite
        /home/winksplorer/.local/lib/python3.11/site-packages/twisted/internet/tcp.py:248:doRead
        /home/winksplorer/.local/lib/python3.11/site-packages/twisted/internet/tcp.py:253:_dataReceived
        /home/winksplorer/Downloads/messenger/client.py:38:dataReceived
        /home/winksplorer/.local/lib/python3.11/site-packages/CTkMessagebox/ctkmessagebox.py:192:__init__
        /home/winksplorer/.local/lib/python3.11/site-packages/CTkMessagebox/ctkmessagebox.py:335:load_icon
        /home/winksplorer/.local/lib/python3.11/site-packages/PIL/Image.py:3218:open
        ]
2023-07-20 21:12:25-0700 [-] Stopping factory <__main__.MessagingClientFactory object at 0x7f339f3bf690>
```

**Comment by IanBotashev** [comment]
Fixed with the previous commit; icon for a client error popup was not set to the proper name.
